# Configuration Settings for ZED-F9P device
ublox_gps_node:
  ros__parameters:
    debug: 0                    # Range 0-4 (0 means no debug statements will print)
    device: /dev/tty_ZED_F9P
    frame_id: gps_link
    uart1:
      baudrate: 115200

    # TMODE3 Config
    tmode3: 0                   # 0 = Disabled (Rover), 1 = Survey-In (Base Station)
    config_on_startup: false    # Whether to configure the ublox on startup

    inf:
      all: false                   # Whether to display all INF messages in console
    
    publish:
      all: false
      nav:
        all: false
        att: true
        pvt: true
        relposned: false
        status: true
      nmea: true

      esf:
        ins: false
        status: false